server:
  port: 8080
spring:
  profiles:
    active: dev
  session:
    timeout: 10
---
spring:
  profiles: dev
  datasource:
#      url: jdbc:mysql://localhost:3306/test
#      username: root
#      password: yang123456
      url: jdbc:mysql://121.41.31.76:3306/yijiayou_rds2?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: yijiayou
      driver-class-name: com.mysql.jdbc.Driver
      #连接池配置
      max-idle: 5
      max-wait: 10
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      #获取连接时候验证，会影响性能
      test-on-borrow: false
      #验证连接的有效性
      test-while-idle: true
      #在连接归还到连接池时是否测试该连接
      test-on-return: false
      #空闲连接回收的时间间隔，与test-while-idle一起使用，设置5分钟
      time-between-eviction-runs-millis: 300000
      #连接池空闲连接的有效时间 ，设置30分钟
      min-evictable-idle-time-millis: 1800000
      jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=0)

# REDIS (RedisProperties)
  redis:
      database: 0 # Database index used by the connection factory.
      host: 121.41.31.76 # Redis server host.
      password: redispass # Login password of the redis server.
      port: 6379 # Redis server port.
      timeout: 3000 # Connection timeout.
      jedis.pool.max-active: 8 # Max number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
      jedis.pool.max-idle: 8 # Max number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
      jedis.pool.max-wait: -1ms # Maximum amount of time a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
      jedis.pool.min-idle: 0 # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.
      lettuce.pool.max-active: 8 # Maximum number of connections that can be allocated by the pool at a given time. Use a negative value for no limit.
      lettuce.pool.max-idle: 8 # Maximum number of "idle" connections in the pool. Use a negative value to indicate an unlimited number of idle connections.
      lettuce.pool.max-wait: -1ms # Maximum amount of time a connection allocation should block before throwing an exception when the pool is exhausted. Use a negative value to block indefinitely.
      lettuce.pool.min-idle: 0 # Target for the minimum number of idle connections to maintain in the pool. This setting only has an effect if it is positive.
      lettuce.shutdown-timeout: 100ms # Shutdown timeout.
      #url:  # Connection URL. Overrides host, port, and password. User is ignored. Example: redis://user:password@example.com:6379
      #sentinel.master:  # Name of the Redis server.
      #sentinel.nodes:  # Comma-separated list of "host:port" pairs.
      #ssl: false # Whether to enable SSL support.
      #cluster.max-redirects:  # Maximum number of redirects to follow when executing commands across the cluster.
      #cluster.nodes:  # Comma-separated list of "host:port" pairs to bootstrap from.


server:
  port: 8081

mybatis:
  mapper-locations: classpath:top/young/analysis/mapper/*.xml
  config-location: classpath:mybatis-config.xml





---
spring:
  profiles: prod
server:
  port: 8082
loginuser:
  username: leifeng
  password: 123456
